// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/msaldanha/realChain/ledger (interfaces: Ledger)

// Package tests is a generated GoMock package.
package tests

import (
	gomock "github.com/golang/mock/gomock"
	transaction "github.com/msaldanha/realChain/transaction"
	reflect "reflect"
)

// MockLedger is a mock of Ledger interface
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
}

// MockLedgerMockRecorder is the mock recorder for MockLedger
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// GetAddressStatement mocks base method
func (m *MockLedger) GetAddressStatement(arg0 string) ([]*transaction.Transaction, error) {
	ret := m.ctrl.Call(m, "GetAddressStatement", arg0)
	ret0, _ := ret[0].([]*transaction.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressStatement indicates an expected call of GetAddressStatement
func (mr *MockLedgerMockRecorder) GetAddressStatement(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressStatement", reflect.TypeOf((*MockLedger)(nil).GetAddressStatement), arg0)
}

// GetLastTransaction mocks base method
func (m *MockLedger) GetLastTransaction(arg0 string) (*transaction.Transaction, error) {
	ret := m.ctrl.Call(m, "GetLastTransaction", arg0)
	ret0, _ := ret[0].(*transaction.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTransaction indicates an expected call of GetLastTransaction
func (mr *MockLedgerMockRecorder) GetLastTransaction(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTransaction", reflect.TypeOf((*MockLedger)(nil).GetLastTransaction), arg0)
}

// GetTransaction mocks base method
func (m *MockLedger) GetTransaction(arg0 string) (*transaction.Transaction, error) {
	ret := m.ctrl.Call(m, "GetTransaction", arg0)
	ret0, _ := ret[0].(*transaction.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction
func (mr *MockLedgerMockRecorder) GetTransaction(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedger)(nil).GetTransaction), arg0)
}

// Initialize mocks base method
func (m *MockLedger) Initialize(arg0 *transaction.Transaction) error {
	ret := m.ctrl.Call(m, "Initialize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize
func (mr *MockLedgerMockRecorder) Initialize(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockLedger)(nil).Initialize), arg0)
}

// Register mocks base method
func (m *MockLedger) Register(arg0, arg1 *transaction.Transaction) error {
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockLedgerMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockLedger)(nil).Register), arg0, arg1)
}

// VerifyTransaction mocks base method
func (m *MockLedger) VerifyTransaction(arg0 *transaction.Transaction, arg1 bool) error {
	ret := m.ctrl.Call(m, "VerifyTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyTransaction indicates an expected call of VerifyTransaction
func (mr *MockLedgerMockRecorder) VerifyTransaction(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTransaction", reflect.TypeOf((*MockLedger)(nil).VerifyTransaction), arg0, arg1)
}

// VerifyTransactions mocks base method
func (m *MockLedger) VerifyTransactions(arg0, arg1 *transaction.Transaction) error {
	ret := m.ctrl.Call(m, "VerifyTransactions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyTransactions indicates an expected call of VerifyTransactions
func (mr *MockLedgerMockRecorder) VerifyTransactions(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTransactions", reflect.TypeOf((*MockLedger)(nil).VerifyTransactions), arg0, arg1)
}
