// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_ZERO    Transaction_Type = 0
	Transaction_OPEN    Transaction_Type = 1
	Transaction_SEND    Transaction_Type = 2
	Transaction_RECEIVE Transaction_Type = 3
	Transaction_CHANGE  Transaction_Type = 4
)

var Transaction_Type_name = map[int32]string{
	0: "ZERO",
	1: "OPEN",
	2: "SEND",
	3: "RECEIVE",
	4: "CHANGE",
}
var Transaction_Type_value = map[string]int32{
	"ZERO":    0,
	"OPEN":    1,
	"SEND":    2,
	"RECEIVE": 3,
	"CHANGE":  4,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{10, 0}
}

type RegisterRequest struct {
	SendTx               *Transaction `protobuf:"bytes,1,opt,name=sendTx,proto3" json:"sendTx,omitempty"`
	ReceiveTx            *Transaction `protobuf:"bytes,2,opt,name=receiveTx,proto3" json:"receiveTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSendTx() *Transaction {
	if m != nil {
		return m.SendTx
	}
	return nil
}

func (m *RegisterRequest) GetReceiveTx() *Transaction {
	if m != nil {
		return m.ReceiveTx
	}
	return nil
}

type RegisterResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{1}
}
func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (dst *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(dst, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

type GetLastTransactionRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastTransactionRequest) Reset()         { *m = GetLastTransactionRequest{} }
func (m *GetLastTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionRequest) ProtoMessage()    {}
func (*GetLastTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{2}
}
func (m *GetLastTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionRequest.Unmarshal(m, b)
}
func (m *GetLastTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionRequest.Merge(dst, src)
}
func (m *GetLastTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionRequest.Size(m)
}
func (m *GetLastTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionRequest proto.InternalMessageInfo

func (m *GetLastTransactionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetLastTransactionResult struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetLastTransactionResult) Reset()         { *m = GetLastTransactionResult{} }
func (m *GetLastTransactionResult) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionResult) ProtoMessage()    {}
func (*GetLastTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{3}
}
func (m *GetLastTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionResult.Unmarshal(m, b)
}
func (m *GetLastTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionResult.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionResult.Merge(dst, src)
}
func (m *GetLastTransactionResult) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionResult.Size(m)
}
func (m *GetLastTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionResult proto.InternalMessageInfo

func (m *GetLastTransactionResult) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type GetTransactionRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{4}
}
func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(dst, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetTransactionResult struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTransactionResult) Reset()         { *m = GetTransactionResult{} }
func (m *GetTransactionResult) String() string { return proto.CompactTextString(m) }
func (*GetTransactionResult) ProtoMessage()    {}
func (*GetTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{5}
}
func (m *GetTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionResult.Unmarshal(m, b)
}
func (m *GetTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionResult.Marshal(b, m, deterministic)
}
func (dst *GetTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionResult.Merge(dst, src)
}
func (m *GetTransactionResult) XXX_Size() int {
	return xxx_messageInfo_GetTransactionResult.Size(m)
}
func (m *GetTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionResult proto.InternalMessageInfo

func (m *GetTransactionResult) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type VerifyTransactionRequest struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyTransactionRequest) Reset()         { *m = VerifyTransactionRequest{} }
func (m *VerifyTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionRequest) ProtoMessage()    {}
func (*VerifyTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{6}
}
func (m *VerifyTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionRequest.Unmarshal(m, b)
}
func (m *VerifyTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionRequest.Merge(dst, src)
}
func (m *VerifyTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionRequest.Size(m)
}
func (m *VerifyTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionRequest proto.InternalMessageInfo

func (m *VerifyTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type VerifyTransactionResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionResult) Reset()         { *m = VerifyTransactionResult{} }
func (m *VerifyTransactionResult) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionResult) ProtoMessage()    {}
func (*VerifyTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{7}
}
func (m *VerifyTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionResult.Unmarshal(m, b)
}
func (m *VerifyTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionResult.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionResult.Merge(dst, src)
}
func (m *VerifyTransactionResult) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionResult.Size(m)
}
func (m *VerifyTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionResult proto.InternalMessageInfo

type VerifyTransactionsRequest struct {
	SendTx               *Transaction `protobuf:"bytes,1,opt,name=sendTx,proto3" json:"sendTx,omitempty"`
	ReceiveTx            *Transaction `protobuf:"bytes,2,opt,name=receiveTx,proto3" json:"receiveTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyTransactionsRequest) Reset()         { *m = VerifyTransactionsRequest{} }
func (m *VerifyTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionsRequest) ProtoMessage()    {}
func (*VerifyTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{8}
}
func (m *VerifyTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionsRequest.Unmarshal(m, b)
}
func (m *VerifyTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionsRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionsRequest.Merge(dst, src)
}
func (m *VerifyTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionsRequest.Size(m)
}
func (m *VerifyTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionsRequest proto.InternalMessageInfo

func (m *VerifyTransactionsRequest) GetSendTx() *Transaction {
	if m != nil {
		return m.SendTx
	}
	return nil
}

func (m *VerifyTransactionsRequest) GetReceiveTx() *Transaction {
	if m != nil {
		return m.ReceiveTx
	}
	return nil
}

type VerifyTransactionsResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionsResult) Reset()         { *m = VerifyTransactionsResult{} }
func (m *VerifyTransactionsResult) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionsResult) ProtoMessage()    {}
func (*VerifyTransactionsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{9}
}
func (m *VerifyTransactionsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionsResult.Unmarshal(m, b)
}
func (m *VerifyTransactionsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionsResult.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionsResult.Merge(dst, src)
}
func (m *VerifyTransactionsResult) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionsResult.Size(m)
}
func (m *VerifyTransactionsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionsResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionsResult proto.InternalMessageInfo

type Transaction struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Type                 Transaction_Type `protobuf:"varint,2,opt,name=type,proto3,enum=Transaction_Type" json:"type,omitempty"`
	Address              []byte           `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Representative       []byte           `protobuf:"bytes,4,opt,name=Representative,proto3" json:"Representative,omitempty"`
	Previous             []byte           `protobuf:"bytes,5,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Link                 []byte           `protobuf:"bytes,6,opt,name=Link,proto3" json:"Link,omitempty"`
	Balance              float64          `protobuf:"fixed64,7,opt,name=Balance,proto3" json:"Balance,omitempty"`
	PowTarget            int32            `protobuf:"varint,8,opt,name=PowTarget,proto3" json:"PowTarget,omitempty"`
	PowNonce             int64            `protobuf:"varint,9,opt,name=PowNonce,proto3" json:"PowNonce,omitempty"`
	Hash                 []byte           `protobuf:"bytes,10,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PubKey               []byte           `protobuf:"bytes,11,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Signature            []byte           `protobuf:"bytes,12,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_51f982d3872cc855, []int{10}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_ZERO
}

func (m *Transaction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction) GetRepresentative() []byte {
	if m != nil {
		return m.Representative
	}
	return nil
}

func (m *Transaction) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Transaction) GetLink() []byte {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *Transaction) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Transaction) GetPowTarget() int32 {
	if m != nil {
		return m.PowTarget
	}
	return 0
}

func (m *Transaction) GetPowNonce() int64 {
	if m != nil {
		return m.PowNonce
	}
	return 0
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResult)(nil), "RegisterResult")
	proto.RegisterType((*GetLastTransactionRequest)(nil), "GetLastTransactionRequest")
	proto.RegisterType((*GetLastTransactionResult)(nil), "GetLastTransactionResult")
	proto.RegisterType((*GetTransactionRequest)(nil), "GetTransactionRequest")
	proto.RegisterType((*GetTransactionResult)(nil), "GetTransactionResult")
	proto.RegisterType((*VerifyTransactionRequest)(nil), "VerifyTransactionRequest")
	proto.RegisterType((*VerifyTransactionResult)(nil), "VerifyTransactionResult")
	proto.RegisterType((*VerifyTransactionsRequest)(nil), "VerifyTransactionsRequest")
	proto.RegisterType((*VerifyTransactionsResult)(nil), "VerifyTransactionsResult")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterEnum("Transaction_Type", Transaction_Type_name, Transaction_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DistributedLedgerClient is the client API for DistributedLedger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistributedLedgerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error)
	GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResult, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResult, error)
	VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResult, error)
	VerifyTransactions(ctx context.Context, in *VerifyTransactionsRequest, opts ...grpc.CallOption) (*VerifyTransactionsResult, error)
}

type distributedLedgerClient struct {
	cc *grpc.ClientConn
}

func NewDistributedLedgerClient(cc *grpc.ClientConn) DistributedLedgerClient {
	return &distributedLedgerClient{cc}
}

func (c *distributedLedgerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, "/DistributedLedger/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedLedgerClient) GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResult, error) {
	out := new(GetLastTransactionResult)
	err := c.cc.Invoke(ctx, "/DistributedLedger/GetLastTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedLedgerClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResult, error) {
	out := new(GetTransactionResult)
	err := c.cc.Invoke(ctx, "/DistributedLedger/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedLedgerClient) VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResult, error) {
	out := new(VerifyTransactionResult)
	err := c.cc.Invoke(ctx, "/DistributedLedger/VerifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedLedgerClient) VerifyTransactions(ctx context.Context, in *VerifyTransactionsRequest, opts ...grpc.CallOption) (*VerifyTransactionsResult, error) {
	out := new(VerifyTransactionsResult)
	err := c.cc.Invoke(ctx, "/DistributedLedger/VerifyTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedLedgerServer is the server API for DistributedLedger service.
type DistributedLedgerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResult, error)
	GetLastTransaction(context.Context, *GetLastTransactionRequest) (*GetLastTransactionResult, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResult, error)
	VerifyTransaction(context.Context, *VerifyTransactionRequest) (*VerifyTransactionResult, error)
	VerifyTransactions(context.Context, *VerifyTransactionsRequest) (*VerifyTransactionsResult, error)
}

func RegisterDistributedLedgerServer(s *grpc.Server, srv DistributedLedgerServer) {
	s.RegisterService(&_DistributedLedger_serviceDesc, srv)
}

func _DistributedLedger_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedLedgerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedLedger/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedLedgerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedLedger_GetLastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedLedgerServer).GetLastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedLedger/GetLastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedLedgerServer).GetLastTransaction(ctx, req.(*GetLastTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedLedger_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedLedgerServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedLedger/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedLedgerServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedLedger_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedLedgerServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedLedger/VerifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedLedgerServer).VerifyTransaction(ctx, req.(*VerifyTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedLedger_VerifyTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedLedgerServer).VerifyTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DistributedLedger/VerifyTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedLedgerServer).VerifyTransactions(ctx, req.(*VerifyTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributedLedger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DistributedLedger",
	HandlerType: (*DistributedLedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DistributedLedger_Register_Handler,
		},
		{
			MethodName: "GetLastTransaction",
			Handler:    _DistributedLedger_GetLastTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _DistributedLedger_GetTransaction_Handler,
		},
		{
			MethodName: "VerifyTransaction",
			Handler:    _DistributedLedger_VerifyTransaction_Handler,
		},
		{
			MethodName: "VerifyTransactions",
			Handler:    _DistributedLedger_VerifyTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_51f982d3872cc855) }

var fileDescriptor_protocol_51f982d3872cc855 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xda, 0x4c,
	0x10, 0xc6, 0xe0, 0x10, 0x18, 0x22, 0xe2, 0xac, 0xfe, 0xe4, 0x5f, 0x5b, 0x39, 0x20, 0xab, 0xad,
	0x50, 0x2b, 0x6d, 0xa5, 0xb4, 0x95, 0x72, 0xe9, 0x21, 0x4d, 0x2c, 0xd2, 0x96, 0x12, 0xe4, 0x58,
	0x39, 0xf4, 0x66, 0x60, 0x4a, 0xac, 0x82, 0x4d, 0x77, 0xd7, 0x04, 0x1e, 0xa7, 0x8f, 0xd8, 0x37,
	0xa8, 0x76, 0x6b, 0x02, 0x05, 0xbb, 0xea, 0xa5, 0xb7, 0x99, 0x6f, 0x66, 0xfc, 0xcd, 0xec, 0xcc,
	0x67, 0x68, 0xce, 0x78, 0x22, 0x93, 0x61, 0x32, 0x61, 0xda, 0x70, 0x87, 0x70, 0xe8, 0xe3, 0x38,
	0x12, 0x12, 0xb9, 0x8f, 0xdf, 0x52, 0x14, 0x92, 0x3c, 0x81, 0xaa, 0xc0, 0x78, 0x14, 0x2c, 0xa8,
	0xd1, 0x32, 0xda, 0x8d, 0xb3, 0x03, 0x16, 0xf0, 0x30, 0x16, 0xe1, 0x50, 0x46, 0x49, 0xec, 0x67,
	0x31, 0xf2, 0x1c, 0xea, 0x1c, 0x87, 0x18, 0xcd, 0x31, 0x58, 0xd0, 0x72, 0x4e, 0xe2, 0x3a, 0xec,
	0x5a, 0xd0, 0x5c, 0x93, 0x88, 0x74, 0x22, 0xdd, 0x37, 0x60, 0x77, 0x50, 0x76, 0x43, 0x21, 0x37,
	0x4b, 0xb2, 0x06, 0x28, 0xec, 0x87, 0xa3, 0x11, 0x47, 0x21, 0x74, 0x07, 0x75, 0x7f, 0xe5, 0xba,
	0xe7, 0x40, 0xf3, 0xca, 0xd4, 0x27, 0xc9, 0x29, 0x94, 0x65, 0x7e, 0xcb, 0x65, 0xb9, 0x70, 0x5f,
	0xc0, 0x71, 0x07, 0xf3, 0xc8, 0x08, 0x98, 0xf7, 0xa1, 0xb8, 0xcf, 0x98, 0xb4, 0xed, 0xbe, 0x86,
	0xff, 0xb6, 0x93, 0xff, 0x82, 0xe2, 0x1c, 0xe8, 0x1d, 0xf2, 0xe8, 0xcb, 0x32, 0x87, 0xe5, 0xcf,
	0x95, 0x36, 0xfc, 0x9f, 0x53, 0xa9, 0x1f, 0x6a, 0x0a, 0xf6, 0x4e, 0x48, 0xfc, 0xbb, 0x4d, 0x39,
	0x39, 0x33, 0x88, 0xac, 0x95, 0xef, 0x15, 0x68, 0x6c, 0xc0, 0xe4, 0x14, 0xea, 0x41, 0x34, 0x45,
	0x21, 0xc3, 0xe9, 0x4c, 0x37, 0x50, 0xf1, 0xd7, 0x00, 0x79, 0x0a, 0xa6, 0x5c, 0xce, 0x50, 0x13,
	0x36, 0xcf, 0x8e, 0x36, 0x09, 0x59, 0xb0, 0x9c, 0xa1, 0xaf, 0xc3, 0x6a, 0xd7, 0x17, 0xd9, 0xae,
	0x2b, 0x2d, 0xa3, 0x7d, 0xe0, 0xaf, 0x5c, 0xf2, 0x4c, 0x1d, 0xcd, 0x8c, 0xa3, 0xc0, 0x58, 0x86,
	0x32, 0x9a, 0x23, 0x35, 0x75, 0xc2, 0x16, 0x4a, 0x1c, 0xa8, 0xf5, 0x39, 0xce, 0xa3, 0x24, 0x15,
	0x74, 0x4f, 0x67, 0x3c, 0xfa, 0x6a, 0xb9, 0xdd, 0x28, 0xfe, 0x4a, 0xab, 0x1a, 0xd7, 0xb6, 0x62,
	0x7c, 0x17, 0x4e, 0xc2, 0x78, 0x88, 0x74, 0xbf, 0x65, 0xb4, 0x0d, 0x7f, 0xe5, 0xaa, 0x81, 0xfa,
	0xc9, 0x43, 0x10, 0xf2, 0x31, 0x4a, 0x5a, 0x6b, 0x19, 0xed, 0x3d, 0x7f, 0x0d, 0x68, 0x9e, 0xe4,
	0xa1, 0x97, 0xa8, 0xc2, 0xba, 0x9e, 0xf6, 0xd1, 0x57, 0x3c, 0xd7, 0xea, 0x88, 0xe0, 0x17, 0x8f,
	0xb2, 0xc9, 0x09, 0x54, 0xfb, 0xe9, 0xe0, 0x23, 0x2e, 0x69, 0x43, 0xa3, 0x99, 0xa7, 0x58, 0x6e,
	0xa3, 0x71, 0x1c, 0xca, 0x94, 0x23, 0x3d, 0xd0, 0xa1, 0x35, 0xe0, 0xbe, 0x05, 0x53, 0xbd, 0x0e,
	0xa9, 0x81, 0xf9, 0xd9, 0xf3, 0x6f, 0xac, 0x92, 0xb2, 0x6e, 0xfa, 0x5e, 0xcf, 0x32, 0x94, 0x75,
	0xeb, 0xf5, 0xae, 0xac, 0x32, 0x69, 0xc0, 0xbe, 0xef, 0x5d, 0x7a, 0xef, 0xef, 0x3c, 0xab, 0x42,
	0x00, 0xaa, 0x97, 0xd7, 0x17, 0xbd, 0x8e, 0x67, 0x99, 0x67, 0x3f, 0xca, 0x70, 0x74, 0x15, 0x09,
	0xc9, 0xa3, 0x41, 0x2a, 0x71, 0xd4, 0xc5, 0xd1, 0x18, 0x39, 0x79, 0x09, 0xb5, 0x95, 0xfe, 0x88,
	0xc5, 0xb6, 0xf4, 0xee, 0x1c, 0xb2, 0x2d, 0x71, 0x96, 0xc8, 0x27, 0x20, 0xbb, 0x3a, 0x23, 0x0e,
	0x2b, 0xd4, 0xac, 0x63, 0xb3, 0x22, 0x61, 0xba, 0x25, 0x72, 0x01, 0xcd, 0xdf, 0xf5, 0x44, 0x4e,
	0x58, 0xae, 0x1a, 0x9d, 0x63, 0x96, 0x27, 0x3c, 0xb7, 0x44, 0x3e, 0xc0, 0xd1, 0xce, 0x61, 0x12,
	0x9b, 0x15, 0x09, 0xce, 0xa1, 0xac, 0x48, 0x51, 0x7a, 0xba, 0xdd, 0x23, 0x27, 0x0e, 0x2b, 0x14,
	0x9a, 0x63, 0xb3, 0x42, 0x55, 0x94, 0x06, 0x55, 0xfd, 0x27, 0x7d, 0xf5, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0xf1, 0x34, 0xcb, 0x5b, 0x05, 0x00, 0x00,
}
