// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/ledgerserver.proto

package ledger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	SendTx               *Transaction `protobuf:"bytes,1,opt,name=sendTx,proto3" json:"sendTx,omitempty"`
	ReceiveTx            *Transaction `protobuf:"bytes,2,opt,name=receiveTx,proto3" json:"receiveTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSendTx() *Transaction {
	if m != nil {
		return m.SendTx
	}
	return nil
}

func (m *RegisterRequest) GetReceiveTx() *Transaction {
	if m != nil {
		return m.ReceiveTx
	}
	return nil
}

type RegisterResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{1}
}
func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (dst *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(dst, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

type GetLastTransactionRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastTransactionRequest) Reset()         { *m = GetLastTransactionRequest{} }
func (m *GetLastTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionRequest) ProtoMessage()    {}
func (*GetLastTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{2}
}
func (m *GetLastTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionRequest.Unmarshal(m, b)
}
func (m *GetLastTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionRequest.Merge(dst, src)
}
func (m *GetLastTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionRequest.Size(m)
}
func (m *GetLastTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionRequest proto.InternalMessageInfo

func (m *GetLastTransactionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetLastTransactionResult struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetLastTransactionResult) Reset()         { *m = GetLastTransactionResult{} }
func (m *GetLastTransactionResult) String() string { return proto.CompactTextString(m) }
func (*GetLastTransactionResult) ProtoMessage()    {}
func (*GetLastTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{3}
}
func (m *GetLastTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastTransactionResult.Unmarshal(m, b)
}
func (m *GetLastTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastTransactionResult.Marshal(b, m, deterministic)
}
func (dst *GetLastTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastTransactionResult.Merge(dst, src)
}
func (m *GetLastTransactionResult) XXX_Size() int {
	return xxx_messageInfo_GetLastTransactionResult.Size(m)
}
func (m *GetLastTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastTransactionResult proto.InternalMessageInfo

func (m *GetLastTransactionResult) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type GetTransactionRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{4}
}
func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(dst, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetTransactionResult struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTransactionResult) Reset()         { *m = GetTransactionResult{} }
func (m *GetTransactionResult) String() string { return proto.CompactTextString(m) }
func (*GetTransactionResult) ProtoMessage()    {}
func (*GetTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{5}
}
func (m *GetTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionResult.Unmarshal(m, b)
}
func (m *GetTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionResult.Marshal(b, m, deterministic)
}
func (dst *GetTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionResult.Merge(dst, src)
}
func (m *GetTransactionResult) XXX_Size() int {
	return xxx_messageInfo_GetTransactionResult.Size(m)
}
func (m *GetTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionResult proto.InternalMessageInfo

func (m *GetTransactionResult) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type VerifyTransactionRequest struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyTransactionRequest) Reset()         { *m = VerifyTransactionRequest{} }
func (m *VerifyTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionRequest) ProtoMessage()    {}
func (*VerifyTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{6}
}
func (m *VerifyTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionRequest.Unmarshal(m, b)
}
func (m *VerifyTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionRequest.Merge(dst, src)
}
func (m *VerifyTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionRequest.Size(m)
}
func (m *VerifyTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionRequest proto.InternalMessageInfo

func (m *VerifyTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type VerifyTransactionResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTransactionResult) Reset()         { *m = VerifyTransactionResult{} }
func (m *VerifyTransactionResult) String() string { return proto.CompactTextString(m) }
func (*VerifyTransactionResult) ProtoMessage()    {}
func (*VerifyTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{7}
}
func (m *VerifyTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTransactionResult.Unmarshal(m, b)
}
func (m *VerifyTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTransactionResult.Marshal(b, m, deterministic)
}
func (dst *VerifyTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTransactionResult.Merge(dst, src)
}
func (m *VerifyTransactionResult) XXX_Size() int {
	return xxx_messageInfo_VerifyTransactionResult.Size(m)
}
func (m *VerifyTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTransactionResult proto.InternalMessageInfo

type VerifyRequest struct {
	SendTx               *Transaction `protobuf:"bytes,1,opt,name=sendTx,proto3" json:"sendTx,omitempty"`
	ReceiveTx            *Transaction `protobuf:"bytes,2,opt,name=receiveTx,proto3" json:"receiveTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{8}
}
func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(dst, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetSendTx() *Transaction {
	if m != nil {
		return m.SendTx
	}
	return nil
}

func (m *VerifyRequest) GetReceiveTx() *Transaction {
	if m != nil {
		return m.ReceiveTx
	}
	return nil
}

type VerifyResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResult) Reset()         { *m = VerifyResult{} }
func (m *VerifyResult) String() string { return proto.CompactTextString(m) }
func (*VerifyResult) ProtoMessage()    {}
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{9}
}
func (m *VerifyResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResult.Unmarshal(m, b)
}
func (m *VerifyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResult.Marshal(b, m, deterministic)
}
func (dst *VerifyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResult.Merge(dst, src)
}
func (m *VerifyResult) XXX_Size() int {
	return xxx_messageInfo_VerifyResult.Size(m)
}
func (m *VerifyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResult proto.InternalMessageInfo

type GetAddressStatementRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressStatementRequest) Reset()         { *m = GetAddressStatementRequest{} }
func (m *GetAddressStatementRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddressStatementRequest) ProtoMessage()    {}
func (*GetAddressStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{10}
}
func (m *GetAddressStatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressStatementRequest.Unmarshal(m, b)
}
func (m *GetAddressStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressStatementRequest.Marshal(b, m, deterministic)
}
func (dst *GetAddressStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressStatementRequest.Merge(dst, src)
}
func (m *GetAddressStatementRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddressStatementRequest.Size(m)
}
func (m *GetAddressStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressStatementRequest proto.InternalMessageInfo

func (m *GetAddressStatementRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetAddressStatementResult struct {
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAddressStatementResult) Reset()         { *m = GetAddressStatementResult{} }
func (m *GetAddressStatementResult) String() string { return proto.CompactTextString(m) }
func (*GetAddressStatementResult) ProtoMessage()    {}
func (*GetAddressStatementResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledgerserver_fe3ec0588a3116af, []int{11}
}
func (m *GetAddressStatementResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressStatementResult.Unmarshal(m, b)
}
func (m *GetAddressStatementResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressStatementResult.Marshal(b, m, deterministic)
}
func (dst *GetAddressStatementResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressStatementResult.Merge(dst, src)
}
func (m *GetAddressStatementResult) XXX_Size() int {
	return xxx_messageInfo_GetAddressStatementResult.Size(m)
}
func (m *GetAddressStatementResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressStatementResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressStatementResult proto.InternalMessageInfo

func (m *GetAddressStatementResult) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "ledger.RegisterRequest")
	proto.RegisterType((*RegisterResult)(nil), "ledger.RegisterResult")
	proto.RegisterType((*GetLastTransactionRequest)(nil), "ledger.GetLastTransactionRequest")
	proto.RegisterType((*GetLastTransactionResult)(nil), "ledger.GetLastTransactionResult")
	proto.RegisterType((*GetTransactionRequest)(nil), "ledger.GetTransactionRequest")
	proto.RegisterType((*GetTransactionResult)(nil), "ledger.GetTransactionResult")
	proto.RegisterType((*VerifyTransactionRequest)(nil), "ledger.VerifyTransactionRequest")
	proto.RegisterType((*VerifyTransactionResult)(nil), "ledger.VerifyTransactionResult")
	proto.RegisterType((*VerifyRequest)(nil), "ledger.VerifyRequest")
	proto.RegisterType((*VerifyResult)(nil), "ledger.VerifyResult")
	proto.RegisterType((*GetAddressStatementRequest)(nil), "ledger.GetAddressStatementRequest")
	proto.RegisterType((*GetAddressStatementResult)(nil), "ledger.GetAddressStatementResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LedgerClient is the client API for Ledger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error)
	GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResult, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResult, error)
	VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResult, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResult, error)
	GetAddressStatement(ctx context.Context, in *GetAddressStatementRequest, opts ...grpc.CallOption) (*GetAddressStatementResult, error)
}

type ledgerClient struct {
	cc *grpc.ClientConn
}

func NewLedgerClient(cc *grpc.ClientConn) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) GetLastTransaction(ctx context.Context, in *GetLastTransactionRequest, opts ...grpc.CallOption) (*GetLastTransactionResult, error) {
	out := new(GetLastTransactionResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/GetLastTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResult, error) {
	out := new(GetTransactionResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResult, error) {
	out := new(VerifyTransactionResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/VerifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResult, error) {
	out := new(VerifyResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) GetAddressStatement(ctx context.Context, in *GetAddressStatementRequest, opts ...grpc.CallOption) (*GetAddressStatementResult, error) {
	out := new(GetAddressStatementResult)
	err := c.cc.Invoke(ctx, "/ledger.Ledger/GetAddressStatement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServer is the server API for Ledger service.
type LedgerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResult, error)
	GetLastTransaction(context.Context, *GetLastTransactionRequest) (*GetLastTransactionResult, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResult, error)
	VerifyTransaction(context.Context, *VerifyTransactionRequest) (*VerifyTransactionResult, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResult, error)
	GetAddressStatement(context.Context, *GetAddressStatementRequest) (*GetAddressStatementResult, error)
}

func RegisterLedgerServer(s *grpc.Server, srv LedgerServer) {
	s.RegisterService(&_Ledger_serviceDesc, srv)
}

func _Ledger_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_GetLastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).GetLastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/GetLastTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).GetLastTransaction(ctx, req.(*GetLastTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/VerifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).VerifyTransaction(ctx, req.(*VerifyTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_GetAddressStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).GetAddressStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.Ledger/GetAddressStatement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).GetAddressStatement(ctx, req.(*GetAddressStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ledger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Ledger_Register_Handler,
		},
		{
			MethodName: "GetLastTransaction",
			Handler:    _Ledger_GetLastTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Ledger_GetTransaction_Handler,
		},
		{
			MethodName: "VerifyTransaction",
			Handler:    _Ledger_VerifyTransaction_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Ledger_Verify_Handler,
		},
		{
			MethodName: "GetAddressStatement",
			Handler:    _Ledger_GetAddressStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/ledgerserver.proto",
}

func init() {
	proto.RegisterFile("ledger/ledgerserver.proto", fileDescriptor_ledgerserver_fe3ec0588a3116af)
}

var fileDescriptor_ledgerserver_fe3ec0588a3116af = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x5b, 0x6b, 0xe2, 0x40,
	0x14, 0x5e, 0x75, 0xc9, 0xea, 0xd9, 0x5d, 0x77, 0x77, 0xd4, 0x35, 0x86, 0x5d, 0xaa, 0x29, 0x85,
	0x82, 0x60, 0xa9, 0xa5, 0xed, 0x43, 0x29, 0x52, 0x5f, 0x7c, 0x11, 0x0a, 0xa9, 0x94, 0xd2, 0x42,
	0x21, 0x35, 0xa7, 0x1a, 0xb0, 0x49, 0x9d, 0x19, 0x25, 0xfd, 0xc7, 0xfd, 0x19, 0xc5, 0x99, 0x49,
	0xbd, 0xe4, 0x52, 0x9f, 0xfa, 0xa4, 0x99, 0xf3, 0x5d, 0xce, 0x99, 0xf3, 0x31, 0x50, 0x9b, 0xa0,
	0x33, 0x42, 0x7a, 0x20, 0x7f, 0x18, 0xd2, 0x39, 0xd2, 0xd6, 0x33, 0xf5, 0xb9, 0x4f, 0x34, 0x79,
	0x66, 0xe8, 0x0a, 0xc2, 0xa9, 0xed, 0x31, 0x7b, 0xc8, 0x5d, 0xdf, 0x93, 0x08, 0x73, 0x0a, 0xbf,
	0x2c, 0x1c, 0xb9, 0x8c, 0x23, 0xb5, 0x70, 0x3a, 0x43, 0xc6, 0x49, 0x13, 0x34, 0x86, 0x9e, 0x33,
	0x08, 0xf4, 0x4c, 0x3d, 0xb3, 0xff, 0xbd, 0x5d, 0x6a, 0x49, 0x76, 0x6b, 0xb0, 0x64, 0x5b, 0x0a,
	0x42, 0x0e, 0xa1, 0x40, 0x71, 0x88, 0xee, 0x1c, 0x07, 0x81, 0x9e, 0x4d, 0xc6, 0x2f, 0x51, 0xe6,
	0x6f, 0x28, 0x2e, 0x2d, 0xd9, 0x6c, 0xc2, 0xcd, 0x63, 0xa8, 0xf5, 0x90, 0xf7, 0x6d, 0xc6, 0x57,
	0x29, 0xaa, 0x1d, 0x1d, 0xbe, 0xd9, 0x8e, 0x43, 0x91, 0x31, 0xd1, 0x4f, 0xc1, 0x0a, 0x3f, 0xcd,
	0x0e, 0xe8, 0x71, 0xb4, 0x85, 0x24, 0xd9, 0x85, 0x2c, 0x4f, 0x1d, 0x20, 0xcb, 0x03, 0xb3, 0x09,
	0x95, 0x1e, 0xc6, 0x79, 0x12, 0xf8, 0x3a, 0xb6, 0xd9, 0x58, 0x19, 0x8a, 0xff, 0xe6, 0x19, 0x94,
	0x37, 0xc1, 0xdb, 0x3b, 0x75, 0x40, 0xbf, 0x46, 0xea, 0x3e, 0xbe, 0xc4, 0x98, 0x6d, 0x25, 0x50,
	0x83, 0x6a, 0x8c, 0x80, 0xb8, 0x3d, 0x1f, 0x7e, 0xca, 0xd2, 0x67, 0x2d, 0xb0, 0x08, 0x3f, 0x42,
	0x43, 0xd1, 0xc0, 0x09, 0x18, 0x3d, 0xe4, 0x17, 0x72, 0x2b, 0x57, 0xdc, 0xe6, 0xf8, 0x84, 0x1e,
	0xff, 0x78, 0x7f, 0x5d, 0xb1, 0xf6, 0x28, 0x4f, 0x5c, 0xeb, 0x1e, 0xe4, 0x78, 0xb0, 0xa0, 0xe4,
	0x92, 0x3a, 0x5a, 0xd4, 0xdb, 0xaf, 0x39, 0xd0, 0xfa, 0xa2, 0x46, 0xce, 0x21, 0x1f, 0xe6, 0x8a,
	0x54, 0x43, 0xc2, 0x46, 0xb8, 0x8d, 0xbf, 0xd1, 0x82, 0x98, 0xe1, 0x0b, 0xb9, 0x03, 0x12, 0x4d,
	0x13, 0x69, 0x84, 0xf8, 0xc4, 0x80, 0x1a, 0xf5, 0x34, 0x88, 0x12, 0xbf, 0x84, 0xe2, 0x7a, 0x78,
	0xc8, 0xff, 0x15, 0x56, 0x8c, 0xe8, 0xbf, 0xa4, 0xb2, 0x12, 0xbc, 0x81, 0x3f, 0x91, 0x3c, 0x90,
	0xf7, 0x4e, 0x92, 0xb2, 0x66, 0xec, 0xa4, 0x20, 0x94, 0xf2, 0x29, 0x68, 0xb2, 0x48, 0x2a, 0xeb,
	0xe0, 0x50, 0xa3, 0xbc, 0x79, 0xac, 0x88, 0xf7, 0x50, 0x8a, 0x59, 0x27, 0x31, 0x57, 0x26, 0x49,
	0xc8, 0x88, 0xd1, 0x48, 0xc5, 0x48, 0xfd, 0x6e, 0xfe, 0x56, 0x3d, 0x67, 0x0f, 0x9a, 0x78, 0xbb,
	0x8e, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0xa1, 0x0e, 0x1d, 0xfa, 0x04, 0x00, 0x00,
}
