// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/transaction.proto

package ledger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_ZERO    Transaction_Type = 0
	Transaction_OPEN    Transaction_Type = 1
	Transaction_SEND    Transaction_Type = 2
	Transaction_RECEIVE Transaction_Type = 3
	Transaction_CHANGE  Transaction_Type = 4
)

var Transaction_Type_name = map[int32]string{
	0: "ZERO",
	1: "OPEN",
	2: "SEND",
	3: "RECEIVE",
	4: "CHANGE",
}
var Transaction_Type_value = map[string]int32{
	"ZERO":    0,
	"OPEN":    1,
	"SEND":    2,
	"RECEIVE": 3,
	"CHANGE":  4,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_f9a352be1c149983, []int{0, 0}
}

type Transaction struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Type                 Transaction_Type `protobuf:"varint,2,opt,name=type,proto3,enum=ledger.Transaction_Type" json:"type,omitempty"`
	Address              []byte           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Representative       []byte           `protobuf:"bytes,4,opt,name=representative,proto3" json:"representative,omitempty"`
	Previous             []byte           `protobuf:"bytes,5,opt,name=previous,proto3" json:"previous,omitempty"`
	Link                 []byte           `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	Balance              float64          `protobuf:"fixed64,7,opt,name=balance,proto3" json:"balance,omitempty"`
	PowTarget            int32            `protobuf:"varint,8,opt,name=powTarget,proto3" json:"powTarget,omitempty"`
	PowNonce             int64            `protobuf:"varint,9,opt,name=powNonce,proto3" json:"powNonce,omitempty"`
	Hash                 []byte           `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	PubKey               []byte           `protobuf:"bytes,11,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature            []byte           `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_f9a352be1c149983, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_ZERO
}

func (m *Transaction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Transaction) GetRepresentative() []byte {
	if m != nil {
		return m.Representative
	}
	return nil
}

func (m *Transaction) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Transaction) GetLink() []byte {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *Transaction) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Transaction) GetPowTarget() int32 {
	if m != nil {
		return m.PowTarget
	}
	return 0
}

func (m *Transaction) GetPowNonce() int64 {
	if m != nil {
		return m.PowNonce
	}
	return 0
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "ledger.Transaction")
	proto.RegisterEnum("ledger.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
}

func init() {
	proto.RegisterFile("ledger/transaction.proto", fileDescriptor_transaction_f9a352be1c149983)
}

var fileDescriptor_transaction_f9a352be1c149983 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x6d, 0xd2, 0x34, 0x9d, 0x96, 0x12, 0xf6, 0xf0, 0xb2, 0x88, 0x87, 0xd0, 0x83,
	0xe4, 0x20, 0x11, 0xf4, 0xec, 0x41, 0x6b, 0x50, 0x11, 0x52, 0x89, 0xc1, 0x43, 0x6f, 0xdb, 0x76,
	0x68, 0x83, 0x6d, 0x76, 0xd9, 0xdd, 0xb6, 0xf4, 0x1b, 0xf9, 0x31, 0x65, 0xb7, 0x7f, 0x22, 0xde,
	0x9e, 0xe7, 0x37, 0xb3, 0xf3, 0x30, 0x3b, 0xc0, 0x56, 0x38, 0x5f, 0xa0, 0xba, 0x31, 0x8a, 0xd7,
	0x9a, 0xcf, 0x4c, 0x25, 0xea, 0x54, 0x2a, 0x61, 0x04, 0x0d, 0x0e, 0x95, 0xe1, 0xb7, 0x07, 0xbd,
	0xb2, 0xa9, 0xd2, 0x4b, 0xe8, 0x96, 0xd5, 0x1a, 0xb5, 0xe1, 0x6b, 0xc9, 0x48, 0x4c, 0x12, 0xaf,
	0x68, 0x00, 0xbd, 0x06, 0xdf, 0xec, 0x25, 0xb2, 0x56, 0x4c, 0x92, 0xc1, 0x2d, 0x4b, 0x0f, 0x43,
	0xd2, 0x5f, 0x03, 0xd2, 0x72, 0x2f, 0xb1, 0x70, 0x5d, 0x94, 0x41, 0x87, 0xcf, 0xe7, 0x0a, 0xb5,
	0x66, 0x5e, 0x4c, 0x92, 0x7e, 0x71, 0xb2, 0xf4, 0x0a, 0x06, 0x0a, 0xa5, 0x42, 0x8d, 0xb5, 0xe1,
	0xa6, 0xda, 0x22, 0xf3, 0x5d, 0xc3, 0x1f, 0x4a, 0x2f, 0x20, 0x94, 0x0a, 0xb7, 0x95, 0xd8, 0x68,
	0xd6, 0x76, 0x1d, 0x67, 0x4f, 0x29, 0xf8, 0xab, 0xaa, 0xfe, 0x62, 0x81, 0xe3, 0x4e, 0xdb, 0xc4,
	0x29, 0x5f, 0xf1, 0x7a, 0x86, 0xac, 0x13, 0x93, 0x84, 0x14, 0x27, 0x6b, 0xf7, 0x92, 0x62, 0x57,
	0x72, 0xb5, 0x40, 0xc3, 0xc2, 0x98, 0x24, 0xed, 0xa2, 0x01, 0x2e, 0x47, 0xec, 0x72, 0x61, 0x1f,
	0x76, 0xdd, 0xd2, 0x67, 0x6f, 0x73, 0x96, 0x5c, 0x2f, 0x19, 0x1c, 0x72, 0xac, 0xa6, 0xff, 0x21,
	0x90, 0x9b, 0xe9, 0x1b, 0xee, 0x59, 0xcf, 0xd1, 0xa3, 0xb3, 0x29, 0xba, 0x5a, 0xd4, 0xdc, 0x6c,
	0x14, 0xb2, 0xbe, 0x2b, 0x35, 0x60, 0x78, 0x0f, 0xbe, 0xfd, 0x1d, 0x1a, 0x82, 0x3f, 0xc9, 0x8a,
	0x71, 0xf4, 0xcf, 0xaa, 0xf1, 0x7b, 0x96, 0x47, 0xc4, 0xaa, 0x8f, 0x2c, 0x7f, 0x8a, 0x5a, 0xb4,
	0x07, 0x9d, 0x22, 0x1b, 0x65, 0xaf, 0x9f, 0x59, 0xe4, 0x51, 0x80, 0x60, 0xf4, 0xf2, 0x90, 0x3f,
	0x67, 0x91, 0xff, 0x18, 0x4e, 0x8e, 0x47, 0x9b, 0x06, 0xee, 0x86, 0x77, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0x69, 0x8e, 0x2f, 0xdf, 0x01, 0x00, 0x00,
}
