// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/transaction.proto

package ledger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_ZERO    Transaction_Type = 0
	Transaction_OPEN    Transaction_Type = 1
	Transaction_SEND    Transaction_Type = 2
	Transaction_RECEIVE Transaction_Type = 3
	Transaction_CHANGE  Transaction_Type = 4
)

var Transaction_Type_name = map[int32]string{
	0: "ZERO",
	1: "OPEN",
	2: "SEND",
	3: "RECEIVE",
	4: "CHANGE",
}
var Transaction_Type_value = map[string]int32{
	"ZERO":    0,
	"OPEN":    1,
	"SEND":    2,
	"RECEIVE": 3,
	"CHANGE":  4,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_3dc6c13d78351316, []int{0, 0}
}

type Transaction struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 Transaction_Type `protobuf:"varint,2,opt,name=type,proto3,enum=ledger.Transaction_Type" json:"type,omitempty"`
	Address              string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Previous             string           `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	Link                 string           `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Balance              float64          `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	PowTarget            int32            `protobuf:"varint,7,opt,name=powTarget,proto3" json:"powTarget,omitempty"`
	PowNonce             int64            `protobuf:"varint,8,opt,name=powNonce,proto3" json:"powNonce,omitempty"`
	Hash                 string           `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	PubKey               string           `protobuf:"bytes,10,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature            string           `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_3dc6c13d78351316, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_ZERO
}

func (m *Transaction) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *Transaction) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Transaction) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Transaction) GetPowTarget() int32 {
	if m != nil {
		return m.PowTarget
	}
	return 0
}

func (m *Transaction) GetPowNonce() int64 {
	if m != nil {
		return m.PowNonce
	}
	return 0
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "ledger.Transaction")
	proto.RegisterEnum("ledger.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
}

func init() {
	proto.RegisterFile("ledger/transaction.proto", fileDescriptor_transaction_3dc6c13d78351316)
}

var fileDescriptor_transaction_3dc6c13d78351316 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xcd, 0x4b, 0x3b, 0x31,
	0x10, 0xfd, 0xa5, 0xbb, 0xdd, 0x6e, 0xa7, 0xf0, 0x63, 0xc9, 0x41, 0x06, 0xf1, 0xb0, 0xf4, 0xb4,
	0x07, 0x59, 0x41, 0xcf, 0x1e, 0xb4, 0x06, 0x15, 0x61, 0x2b, 0xb1, 0x78, 0xe8, 0x2d, 0x6d, 0x43,
	0xbb, 0xd8, 0x6e, 0x42, 0x92, 0x5a, 0x7a, 0xf3, 0x4f, 0x97, 0xa4, 0x1f, 0xeb, 0xed, 0x7d, 0x24,
	0xef, 0xcd, 0x30, 0x80, 0x6b, 0xb9, 0x58, 0x4a, 0x73, 0xe3, 0x8c, 0x68, 0xac, 0x98, 0xbb, 0x5a,
	0x35, 0xa5, 0x36, 0xca, 0x29, 0x9a, 0x1c, 0x9c, 0xe1, 0x4f, 0x04, 0x83, 0x49, 0xeb, 0xd2, 0x2b,
	0xe8, 0xbb, 0x7a, 0x23, 0xad, 0x13, 0x1b, 0x8d, 0x24, 0x27, 0x45, 0xc4, 0x5b, 0x81, 0x5e, 0x43,
	0xec, 0xf6, 0x5a, 0x62, 0x27, 0x27, 0xc5, 0xff, 0x5b, 0x2c, 0x0f, 0x21, 0xe5, 0x9f, 0x80, 0x72,
	0xb2, 0xd7, 0x92, 0x87, 0x57, 0x14, 0xa1, 0x27, 0x16, 0x0b, 0x23, 0xad, 0xc5, 0x28, 0x27, 0x45,
	0x9f, 0x9f, 0x28, 0xbd, 0x84, 0x54, 0x1b, 0xf9, 0x5d, 0xab, 0xad, 0xc5, 0x38, 0x58, 0x67, 0x4e,
	0x29, 0xc4, 0xeb, 0xba, 0xf9, 0xc2, 0x6e, 0xd0, 0x03, 0xf6, 0x49, 0x33, 0xb1, 0x16, 0xcd, 0x5c,
	0x62, 0x92, 0x93, 0x82, 0xf0, 0x13, 0xf5, 0xf3, 0x6a, 0xb5, 0x9b, 0x08, 0xb3, 0x94, 0x0e, 0x7b,
	0x39, 0x29, 0xba, 0xbc, 0x15, 0x42, 0x8f, 0xda, 0x55, 0xca, 0x7f, 0x4c, 0xc3, 0x32, 0x67, 0xee,
	0x7b, 0x56, 0xc2, 0xae, 0xb0, 0x7f, 0xe8, 0xf1, 0x98, 0x5e, 0x40, 0xa2, 0xb7, 0xb3, 0x37, 0xb9,
	0x47, 0x08, 0xea, 0x91, 0xf9, 0x16, 0x5b, 0x2f, 0x1b, 0xe1, 0xb6, 0x46, 0xe2, 0x20, 0x58, 0xad,
	0x30, 0xbc, 0x87, 0xd8, 0x6f, 0x4d, 0x53, 0x88, 0xa7, 0x8c, 0x8f, 0xb3, 0x7f, 0x1e, 0x8d, 0xdf,
	0x59, 0x95, 0x11, 0x8f, 0x3e, 0x58, 0xf5, 0x94, 0x75, 0xe8, 0x00, 0x7a, 0x9c, 0x8d, 0xd8, 0xeb,
	0x27, 0xcb, 0x22, 0x0a, 0x90, 0x8c, 0x5e, 0x1e, 0xaa, 0x67, 0x96, 0xc5, 0x8f, 0xe9, 0xf4, 0x78,
	0x8c, 0x59, 0x12, 0x6e, 0x73, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xc3, 0x49, 0x9d, 0xb7,
	0x01, 0x00, 0x00,
}
